build_project:
  stage: build
  parallel:
    matrix:
      - PROJECT: authz
      - PROJECT: comments
      - PROJECT: core
      - PROJECT: formatting
      - PROJECT: gateway
      - PROJECT: websocket
  rules:
    - if: $CI_MERGE_REQUEST_ID || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_REF_NAME =~ /^v[0-9]+/ || $CI_COMMIT_REF_NAME =~ /^[0-9]+\.[0-9]+$/
      changes:
        - "*"
        - ".gitlab/ci/**/*"
        - "$PROJECT/**/*"
      when: on_success
  trigger:
    include: "$PROJECT/.gitlab-ci.yml"
    strategy: depend
