build_project:
  stage: build
  parallel:
    matrix:
      - PROJECT: authz
      - PROJECT: comments
      - PROJECT: core
      - PROJECT: formatting
      - PROJECT: gateway
      - PROJECT: websocket
  rules:
    - if: $CI_MERGE_REQUEST_ID || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_REF_NAME =~ /^v[0-9]+/ || $CI_COMMIT_REF_NAME =~ /^[0-9]+\.[0-9]+$/
      changes:
        - "*"
        - ".gitlab/ci/**/*"
        - "$PROJECT/**/*"
      when: on_success
  trigger:
    include: "$PROJECT/.gitlab-ci.yml"
    strategy: depend

build_dependency_image:
  stage: deploy
  needs: []
  parallel:
    matrix:
      - IMAGE_NAME: arsnova-proxy
      - IMAGE_NAME: rabbitmq-stomp
        IMAGE_VARIANT:
          - ""
          - "management"
      - IMAGE_NAME: couchdb
  rules:
    - if: $CI_MERGE_REQUEST_ID
      changes:
        - ".docker/images/*"
        - ".docker/images/$IMAGE_NAME/*"
      when: manual
      variables:
        IMAGE_TAG_AFFIX: $CI_COMMIT_REF_NAME
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      changes:
        - ".docker/images/*"
        - ".docker/images/$IMAGE_NAME/*"
      when: on_success
  trigger:
    include: ".docker/images/.gitlab-ci.yml"
    strategy: depend
