version: "3"
services:
  couchdb:
    image: couchdb:2.3
    environment:
      COUCHDB_USER: arsnova
      COUCHDB_PASSWORD: arsnova
    volumes:
      - couchdb_data:/opt/couchdb/data
  postgresql:
    image: postgres:12.1
    environment:
      POSTGRES_DB: arsnovacomment
      POSTGRES_USER: arsnovacomment
      POSTGRES_PASSWORD: arsnovacomment
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  rabbitmq:
    image: registry.gitlab.com/particify/devops/docker-orchestration/rabbitmq-stomp:3.8
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  arsnova-backend-core:
    image: registry.gitlab.com/arsnova/arsnova-backend:master
    depends_on:
      - couchdb
      - rabbitmq
    environment:
      SYSTEM_COUCHDB_HOST: couchdb
      SYSTEM_COUCHDB_USERNAME: arsnova
      SYSTEM_COUCHDB_PASSWORD: arsnova
      SYSTEM_COUCHDB_CREATEDB: "true"
      SYSTEM_MESSAGE_BROKER_RELAY_ENABLED: "true"
      SYSTEM_MESSAGE_BROKER_RELAY_HOST: rabbitmq
      SYSTEM_MESSAGE_BROKER_RELAY_USERNAME: guest
      SYSTEM_MESSAGE_BROKER_RELAY_PASSWORD: guest
      SECURITY_JWT_SECRET: secret
      UI_SLOGAN: powered by particify.de
  arsnova-comment-service:
    image: registry.gitlab.com/arsnova/arsnova-comment-service:master
    depends_on:
      - postgresql
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/arsnovacomment
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
  arsnova-web:
    #image: registry.gitlab.com/arsnova/arsnova-webclient:master
    image: registry.gitlab.com/arsnova/arsnova-webclient:dev-use-ws-proxy
  arsnova-web-legacy:
    image: registry.gitlab.com/particify/devops/docker-orchestration/arsnova-mobile:2.7.1
  arsnova-proxy:
    image: registry.gitlab.com/particify/devops/docker-orchestration/nginx-proxy:stable
    depends_on:
      - arsnova-backend-core
      - arsnova-comment-service
      - arsnova-web
volumes:
  couchdb_data:
  postgresql_data:
