version: "3"
services:
  couchdb:
    ports:
      - 127.0.0.1:5984:5984
  postgresql_auth:
    ports:
      - 127.0.0.1:5432:5432
  postgresql_comment:
    ports:
      - 127.0.0.1:5433:5432
  rabbitmq:
    #build: ./rabbitmq-stomp
    image: registry.gitlab.com/particify/devops/docker-orchestration/rabbitmq-stomp:3.8-management
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672
      - 127.0.0.1:61613:61613
  arsnova-backend-core:
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8090:8090
  arsnova-ws-gateway:
    ports:
      - 127.0.0.1:8099:8080
  arsnova-auth-service:
    ports:
      - 127.0.0.1:8092:8080
  arsnova-comment-service:
    ports:
      - 127.0.0.1:8088:8080
  arsnova-web:
    ports:
      - 127.0.0.1:8081:80
  arsnova-web-legacy:
    ports:
      - 127.0.0.1:8082:80
  arsnova-proxy:
    #image: nginx:stable
    ports:
      - 127.0.0.1:$PORT:80
    #volumes:
    #  - ./nginx-proxy/conf.d:/etc/nginx/conf.d
