server:
  port: 9090
---
spring:
  cloud:
    gateway:
      routes:
        - id: test
          uri: http://localhost:8088/
          predicates:
            - Path=/{roomId}/comment/**
          filters:
            - name: AuthFilter
            - name: RoomIdFilter
---
security:
  jwt:
    public-secret: "secret"
    internal-secret: "secret"
    serverId: arsnova.gateway.v3:com.example
---
http-client:
  auth-service: "http://127.0.0.1:8092"
---
logging:
  level:
    org.springframework.cloud.gateway: TRACE
