server:
  port: 9090
---
routing:
  endpoints:
    core: "http://localhost:8080/"
    comment-service: "http://localhost:8088/"
    roomaccess-service: "http://localhost:8092/"
    formatting-service: "http://localhost:3020/"
---
security:
  jwt:
    public-secret: "secret"
    internal-secret: "secret"
    serverId: arsnova.gateway.v3:com.example
    validity-period: 5m
---
http-client:
  auth-service: "http://127.0.0.1:8092"
  comment-service: "http://127.0.0.1:8088"
  core: "http://127.0.0.1:8080"
---
logging:
  level:
    org.springframework.cloud.gateway: TRACE
