services:
  couchdb:
    ports:
      - 127.0.0.1:5984:5984
  arsnova-proxy:
    ports:
      - 127.0.0.1:${PORT:-8080}:80
  arsnova-webclient:
    image: devcontainer-arsnova-webclient:$WEBCLIENT_TAG
    build:
      context: ../../../webclient/.devcontainer
      args:
        APP_IMAGE: registry.gitlab.com/particify/dev/foss/arsnova-webclient:$WEBCLIENT_TAG
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ./.git:/workspace/.git
      - ../../../webclient:/workspace/webclient
      - vscode-extensions-webclient:/home/dev/.vscode-server/extensions
  arsnova-server-core:
    image: devcontainer-arsnova-server-core:$CORE_TAG
    build:
      context: ../../../core/.devcontainer
      args:
        APP_IMAGE: registry.gitlab.com/particify/dev/foss/arsnova-server/core:$CORE_TAG
        INSTALL_MAVEN: "true"
        MAVEN_VERSION: $MAVEN_VERSION
    environment:
      SERVER_PORT: ""
      SPRING_APPLICATION_JSON: '{"server": {"port": "8080"}}'
      SECURITY_CORSORIGINS_0: http://localhost
      SECURITY_CORSORIGINS_1: http://localhost:4200
      GRADLE_RO_DEP_CACHE: /home/dev/.gradle-ro-dep-cache
    volumes:
      - ../../..:/workspace
      - gradle-workspace-core:/workspace/.gradle
      - gradle-cache-core:/home/dev/.gradle/caches
      - gradle-ro-dep-cache:/home/dev/.gradle-ro-dep-cache:ro
      - gradle-wrapper:/home/dev/.gradle/wrapper
      - vscode-extensions-core:/home/dev/.vscode-server/extensions
  arsnova-server-gateway:
    image: devcontainer-arsnova-server-gateway:$GATEWAY_TAG
    build:
      context: ../../../gateway/.devcontainer
      args:
        APP_IMAGE: registry.gitlab.com/particify/dev/foss/arsnova-server/gateway:$GATEWAY_TAG
        INSTALL_MAVEN: "true"
        MAVEN_VERSION: $MAVEN_VERSION
    environment:
      SERVER_PORT: ""
      SPRING_APPLICATION_JSON: '{"server": {"port": "8080"}}'
      GRADLE_RO_DEP_CACHE: /home/dev/.gradle-ro-dep-cache
    volumes:
      - ../../..:/workspace
      - gradle-workspace-gateway:/workspace/.gradle
      - gradle-cache-gateway:/home/dev/.gradle/caches
      - gradle-ro-dep-cache:/home/dev/.gradle-ro-dep-cache:ro
      - gradle-wrapper:/home/dev/.gradle/wrapper
      - vscode-extensions-gateway:/home/dev/.vscode-server/extensions
  arsnova-server-websocket:
    image: devcontainer-arsnova-server-websocket:$WEBSOCKET_TAG
    build:
      context: ../../../websocket/.devcontainer
      args:
        APP_IMAGE: registry.gitlab.com/particify/dev/foss/arsnova-server/websocket:$WEBSOCKET_TAG
        INSTALL_MAVEN: "true"
        MAVEN_VERSION: $MAVEN_VERSION
    environment:
      SERVER_PORT: ""
      SPRING_APPLICATION_JSON: '{"server": {"port": "8080"}}'
      GRADLE_RO_DEP_CACHE: /home/dev/.gradle-ro-dep-cache
    volumes:
      - ../../..:/workspace
      - gradle-workspace-websocket:/workspace/.gradle
      - gradle-cache-websocket:/home/dev/.gradle/caches
      - gradle-ro-dep-cache:/home/dev/.gradle-ro-dep-cache:ro
      - gradle-wrapper:/home/dev/.gradle/wrapper
      - vscode-extensions-websocket:/home/dev/.vscode-server/extensions
  arsnova-server-authz:
    image: devcontainer-arsnova-server-authz:$AUTHZ_TAG
    build:
      context: ../../../authz/.devcontainer
      args:
        APP_IMAGE: registry.gitlab.com/particify/dev/foss/arsnova-server/authz:$AUTHZ_TAG
        INSTALL_MAVEN: "true"
        MAVEN_VERSION: $MAVEN_VERSION
    environment:
      SERVER_PORT: ""
      SPRING_APPLICATION_JSON: '{"server": {"port": "8080"}}'
      GRADLE_RO_DEP_CACHE: /home/dev/.gradle-ro-dep-cache
      PGHOST: postgresql-authz
      PGDATABASE: arsnovaauth
      PGUSER: arsnovaauth
      PGPASSWORD: arsnovaauth
    volumes:
      - ../../..:/workspace
      - gradle-workspace-authz:/workspace/.gradle
      - gradle-cache-authz:/home/dev/.gradle/caches
      - gradle-ro-dep-cache:/home/dev/.gradle-ro-dep-cache:ro
      - gradle-wrapper:/home/dev/.gradle/wrapper
      - vscode-extensions-authz:/home/dev/.vscode-server/extensions
  arsnova-server-comments:
    image: devcontainer-arsnova-server-comments:$COMMENTS_TAG
    build:
      context: ../../../comments/.devcontainer
      args:
        APP_IMAGE: registry.gitlab.com/particify/dev/foss/arsnova-server/comments:$COMMENTS_TAG
        INSTALL_MAVEN: "true"
        MAVEN_VERSION: $MAVEN_VERSION
    environment:
      SERVER_PORT: ""
      SPRING_APPLICATION_JSON: '{"server": {"port": "8080"}}'
      GRADLE_RO_DEP_CACHE: /home/dev/.gradle-ro-dep-cache
      PGHOST: postgresql-comments
      PGDATABASE: arsnovacomment
      PGUSER: arsnovacomment
      PGPASSWORD: arsnovacomment
    volumes:
      - ../../..:/workspace
      - gradle-workspace-comments:/workspace/.gradle
      - gradle-cache-comments:/home/dev/.gradle/caches
      - gradle-ro-dep-cache:/home/dev/.gradle-ro-dep-cache:ro
      - gradle-wrapper:/home/dev/.gradle/wrapper
      - vscode-extensions-comments:/home/dev/.vscode-server/extensions
  arsnova-server-formatting:
    image: devcontainer-arsnova-server-formatting:$FORMATTING_TAG
    build:
      context: ../../../formatting/.devcontainer
      args:
        APP_IMAGE: registry.gitlab.com/particify/dev/foss/arsnova-server/formatting:$FORMATTING_TAG
    environment:
      PORT: 3000
    volumes:
      - ../../..:/workspace
      - vscode-extensions-formatting:/home/dev/.vscode-server/extensions

volumes:
  gradle-cache-authz:
  gradle-cache-comments:
  gradle-cache-core:
  gradle-cache-gateway:
  gradle-cache-websocket:
  gradle-ro-dep-cache:
  gradle-workspace-authz:
  gradle-workspace-comments:
  gradle-workspace-core:
  gradle-workspace-gateway:
  gradle-workspace-websocket:
  gradle-wrapper:
  vscode-extensions-authz:
  vscode-extensions-comments:
  vscode-extensions-core:
  vscode-extensions-formatting:
  vscode-extensions-gateway:
  vscode-extensions-webclient:
  vscode-extensions-websocket:
