services:
  couchdb:
    ports:
      - 127.0.0.1:5984:5984
  arsnova-proxy:
    ports:
      - 127.0.0.1:${PORT:-8080}:80
  arsnova-web:
    image: devcontainer-arsnova-webclient:$WEB_TAG
    build:
      context: arsnova-webclient/.devcontainer
      args:
        APP_IMAGE: registry.gitlab.com/particify/dev/foss/arsnova-webclient:$WEB_TAG
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ./.git:/workspace/.git
      - ./arsnova-webclient:/workspace/arsnova-webclient
  arsnova-backend-core:
    image: devcontainer-arsnova-backend-core:$CORE_TAG
    build:
      context: arsnova-backend/.devcontainer
      args:
        APP_IMAGE: registry.gitlab.com/particify/dev/foss/arsnova-backend:$CORE_TAG
        INSTALL_MAVEN: "true"
        MAVEN_VERSION: $MAVEN_VERSION
    environment:
      SERVER_PORT: ""
      SPRING_APPLICATION_JSON: '{"server": {"port": "8080"}}'
      SECURITY_CORSORIGINS_0: http://localhost
      SECURITY_CORSORIGINS_1: http://localhost:4200
    volumes:
      - ./.git:/workspace/.git
      - ./arsnova-backend:/workspace/arsnova-backend
      - maven-cache:/home/dev/.m2
  arsnova-http-gateway:
    image: devcontainer-arsnova-http-gateway:$HTTPGW_TAG
    build:
      context: arsnova-http-gateway/.devcontainer
      args:
        APP_IMAGE: registry.gitlab.com/particify/dev/foss/arsnova-http-gateway:$HTTPGW_TAG
        INSTALL_MAVEN: "true"
        MAVEN_VERSION: $MAVEN_VERSION
    environment:
      SERVER_PORT: ""
      SPRING_APPLICATION_JSON: '{"server": {"port": "8080"}}'
    volumes:
      - ./.git:/workspace/.git
      - ./arsnova-http-gateway:/workspace/arsnova-http-gateway
      - maven-cache:/home/dev/.m2
  arsnova-ws-gateway:
    image: devcontainer-arsnova-ws-gateway:$WSGW_TAG
    build:
      context: arsnova-ws-gateway/.devcontainer
      args:
        APP_IMAGE: registry.gitlab.com/particify/dev/foss/arsnova-ws-gateway:$WSGW_TAG
        INSTALL_MAVEN: "true"
        MAVEN_VERSION: $MAVEN_VERSION
    environment:
      SERVER_PORT: ""
      SPRING_APPLICATION_JSON: '{"server": {"port": "8080"}}'
    volumes:
      - ./.git:/workspace/.git
      - ./arsnova-ws-gateway:/workspace/arsnova-ws-gateway
      - maven-cache:/home/dev/.m2
  arsnova-auth-service:
    image: devcontainer-arsnova-auth-service:$AUTH_TAG
    build:
      context: arsnova-auth-service/.devcontainer
      args:
        APP_IMAGE: registry.gitlab.com/particify/dev/foss/arsnova-auth-service:$AUTH_TAG
        INSTALL_MAVEN: "true"
        MAVEN_VERSION: $MAVEN_VERSION
    environment:
      SERVER_PORT: ""
      SPRING_APPLICATION_JSON: '{"server": {"port": "8080"}}'
      PGHOST: postgresql-auth
      PGDATABASE: arsnovaauth
      PGUSER: arsnovaauth
      PGPASSWORD: arsnovaauth
    volumes:
      - ./.git:/workspace/.git
      - ./arsnova-auth-service:/workspace/arsnova-auth-service
      - maven-cache:/home/dev/.m2
  arsnova-comment-service:
    image: devcontainer-arsnova-comment-service:$COMMENT_TAG
    build:
      context: arsnova-comment-service/.devcontainer
      args:
        APP_IMAGE: registry.gitlab.com/particify/dev/foss/arsnova-comment-service:$COMMENT_TAG
        INSTALL_MAVEN: "true"
        MAVEN_VERSION: $MAVEN_VERSION
    environment:
      SERVER_PORT: ""
      SPRING_APPLICATION_JSON: '{"server": {"port": "8080"}}'
      PGHOST: postgresql-comment
      PGDATABASE: arsnovacomment
      PGUSER: arsnovacomment
      PGPASSWORD: arsnovacomment
    volumes:
      - ./.git:/workspace/.git
      - ./arsnova-comment-service:/workspace/arsnova-comment-service
      - maven-cache:/home/dev/.m2
  arsnova-formatting-service:
    image: devcontainer-arsnova-formatting-service:$FORMATTING_TAG
    build:
      context: arsnova-formatting-service/.devcontainer
      args:
        APP_IMAGE: registry.gitlab.com/particify/dev/foss/formatting-service:$FORMATTING_TAG
    environment:
      PORT: 3000
    volumes:
      - ./.git:/workspace/.git
      - ./arsnova-formatting-service:/workspace/arsnova-formatting-service

volumes:
  maven-cache:
