build_docker_image:
  stage: deploy
  needs: []
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  parallel:
    matrix:
      - IMAGE_NAME: arsnova-proxy
      - IMAGE_NAME: rabbitmq-stomp
        IMAGE_VARIANT:
          - ""
          - "management"
      - IMAGE_NAME: couchdb
  rules:
    - if: $CI_MERGE_REQUEST_ID
      changes:
        - ".docker/images/*"
        - ".docker/images/$IMAGE_NAME/*"
      when: manual
      variables:
        IMAGE_TAG_SUFFIX: -$CI_COMMIT_REF_NAME
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      changes:
        - ".docker/images/*"
        - ".docker/images/$IMAGE_NAME/*"
      when: always
  variables:
    KANIKO_CONTEXT: $CI_PROJECT_DIR/.docker/images/$IMAGE_NAME
    KANIKO_DOCKERFILE: $CI_PROJECT_DIR/.docker/images/$IMAGE_NAME/Dockerfile
  allow_failure: true
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - VERSION=$(./.docker/images/version.sh $IMAGE_NAME $IMAGE_VARIANT)
    - if [ -n "$IMAGE_VARIANT" ]; then KANIKO_DOCKERFILE=$KANIKO_CONTEXT/$IMAGE_VARIANT.Dockerfile; fi
    - KANIKO_DESTINATION=$CI_REGISTRY/$CI_PROJECT_PATH/$IMAGE_NAME:$VERSION$IMAGE_TAG_SUFFIX
    - env | grep -E 'IMAGE|KANIKO'
    - /kaniko/executor
      --context "$KANIKO_CONTEXT"
      --dockerfile "$KANIKO_DOCKERFILE"
      --destination "$KANIKO_DESTINATION"
