arsnova:
  alias-words:
    nouns:
      - alpaca
      - armadillo
      - badger
      - barracuda
      - bat
      - bear
      - beaver
      - bison
      - bumblebee
      - butterfly
      - cockatoo
      - chameleon
      - cheetah
      - crocodile
      - deer
      - dolphin
      - dragonfly
      - duck
      - eagle
      - emu
      - elephant
      - falcon
      - ferret
      - flamingo
      - giraffe
      - goose
      - hare
      - hedgehog
      - heron
      - hummingbird
      - ibex
      - iguana
      - jaguar
      - jellyfish
      - kangaroo
      - kiwi
      - koala
      - leopard
      - lion
      - llama
      - lobster
      - lynx
      - meerkat
      - mole
      - narwhal
      - owl
      - peacock
      - pelican
      - penguin
      - pigeon
      - piranha
      - puma
      - racoon
      - seal
      - squirrel
      - starfish
      - swan
      - tapir
      - tiger
      - viper
      - wolf
      - zebra
    special-nouns:
      - mammoth
      - archaeopteryx
      - brachiosaurus
      - brontosaurus
      - pteranodon
      - stegosaurus
      - triceratops
      - tyrannosaurus
      - velociraptor
      - dragon
      - unicorn
      - vampire
      - werewolf
    adjectives:
      - adept
      - adventurous
      - ambitious
      - brilliant
      - brave
      - capable
      - chatty
      - cheerful
      - courageous
      - creative
      - curious
      - decisive
      - determined
      - diligent
      - elegant
      - enthusiastic
      - fabulous
      - focused
      - generous
      - helpful
      - hilarious
      - imaginative
      - ingenious
      - inquisitive
      - insightful
      - inventive
      - knowledgeable
      - observant
      - optimistic
      - passionate
      - patient
      - persistent
      - reliable
      - resourceful
      - responsible
      - sincere
      - swift
      - thoughtful
      - unique
      - versatile
      - vivid
